# Generated by Django 5.2.5 on 2025-08-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=150)),
                ('texto', models.CharField(max_length=1000)),
                ('relevante', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
