# Generated by Django 5.2.5 on 2025-08-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classificacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='relevante',
            new_name='produtivo',
        ),
    ]
