# Generated by Django 5.2.5 on 2025-08-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificacao', '0002_rename_relevante_email_produtivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='emails/'),
        ),
        migrations.AddField(
            model_name='email',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
